### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by TanakaAkihiro** [ptuomola/exercise-tracker#5]
Koodia tarkasteltu 11.08.2021 08:56.

# Koodikatselmointi
Hienoa työtä! Sovellus vaikuttaa kiinnostavalta ja se on toteutettu mainiosti! Koodisi on selkeää ja sovelluslogiikka on eroteltu hyvin käyttöliittymästä. Commitit on pakattu selkeästi aiheittain ja niillä on hyvin kuvaavat nimet. Dokumentaatio on ajantasalla sekä docstringit helpottavat huomattavasti koodin tarkastelua!

## Korjaus- ja parannusehdotuksia
* En löytänyt repositoriostasi tiedostoa schema.sql ja siksi sovelluksen käytössä olevista tietokannoista oli vaikeata hahmottaa niiden kokonaiskuva.
* Aktiviteettien poistaminen olisi hyvä toiminto superuserille.
* Kun sovellusta käyttää pienessä ikkunassa, yläosan painikkeet (Users, Activities, Profile, Logout) katoavat ja niitä ei voi tarkastella sivuvalikosta (kolme vaakaviivaa).

# Tosi hieno projekti! Ei muuta kuin tsemppiä kurssille ja ihanaa loppukesää!!

**Comment by ptuomola** [comment]
Kiitos palautteesta! Tosi hyvä havainto tuo yläosan painikkeiden ongelma. Tämä pitää ehdottomasti korjata! Kiitos ja tsemppiä omaan projektiisi!
