### ISSUE TITLE
Aineopintojen harjoitustyö: Tietokantasovellus, kesä 2021, vertaisarviointi

### ISSUE THREAD

**Issue by katriryt** [ptuomola/exercise-tracker#9]
# Aineopintojen harjoitustyö: Tietokantasovellus, kesä 2021, vertaisarviointi

* Vertaisarvioitavana exercise-tracker, jonka tarkoituksena on käyttäjän kuntoilutottumusten seuraaminen ja tukeminen. 
* Tarkastelu on tehty maanantaina 23.8. klo 15-17 sekä tavallisena että super-käyttäjänä.
* Alla palautetteita arvioinneista. Toivottavasti näistä on hyötyä jatkokehityksessä!

## Vaatimusmäärittely ja sovelluksen suorittaminen Herokussa 
* Sovelluksen suorittaminen: Herokun linkki toimii ja sovelluksen etusivu avautuu! Sovellus toimi moitteettomasti testin aikana. 
* Vaatimusmäärittely: Dokumentaatio on erittäin selkeää; on selvää mitä ollaan tekemässä. Erityiskiitos kommenteista, joilla avattiin github:ssa olevien hakemistojen ja tiedostojen logiikkaa.
* Sovellus on erittäin tyylikkäästi toteutettu ja sitä on mukava käyttää.
    * Boostrapia on käytetty hienosti. Ulkoasu on viimeistelty ja käyttökokemus on erittäin hyvä. 
    * Kautta linjan on selvää, mitä eri sivuilla on tarkoitus tehdä ja mitä toiminnallisuuksia on käytössä.
    * Esim. Virheviestit tulevat kirjautuessa näkyville, jos salasana ei täytä vaatimuksia. Virheilmoitukselta ei kuitenkaan voi välttyä, koska vaatimuksia esim. salasanalle ei kerrota etukäteen. Kysymys: Olisiko tässä paikka esim. pop-upille, jossa vaatimukset kerrottaisiin? 
* Käyttäjänä - ja superkäyttäjänä - aktiviteettien luominen ja editointi sujuvat kätevästi ja yhteenvetotaulut päivittyvät ajan tasalle. Super-käyttäjänä en kuitenkaan pystynyt muokkaamaan aktiviteetin tyyppiä; onko tämä tarkoituskin?
* Yhteenveto omista aktiviteeteista on erittäin selkeä ja mukavaa pystyä näkemään eri aikajaksoille. Idea: Haluaisiko tässä nostaa rimaa ja tehdä yhteenvetonäkymästä listan sijasta visuaalisemman (esim. aktiviteettimäärät yli ajan eri viikkoina tai viikonpäivien mukaan luokiteltuina)?
* Kaiken kaikkiaan todella hieno sovellus, jota on ilo käyttää. 

## Sovelluksen koodi ja tietokannan rakenne
* Sovelluksen koodi on todella ammattimaisesti tehtyä ja erittäin siistiä. Logiikkaa oli helppo seurata. 
* Ulkoisia paketteja, esim. WTForms, alembic, on käytetty todella ansiokkaasti.
* Tietokannan rakenne käy ilmi schema.sql:stä. Idea: jos haluaa viedä vielä eteenpäin (joskin työ täyttää varmasti nytkin kaikki vaatimukset): olisiko tarvetta pitää kirjaa sovelluksen käytöstä, esim. loggaamalla käyttäjän log-in/log-out aikoja?
* Jos jotakin pientä haluaa koodissa hioa, joissakin metodeissa rivit (esim. exercise.py, activity.py) ovat varsin pitkiä, näitä voisi jakaa eri riveille.

Hienoa työtä!

**Comment by ptuomola** [comment]
Hei - kiitos palautteesta! Formatoin tuota koodia paremmin, joten nyt on helppolukuisempaa. Ja noita lisätoiminnallisuuksia toki olisi kiva toteuttaa, mutta katsotaan paljonko tässä vielä ehtii ennen kurssin loppua :-). Kiitos ja tsemppiä omaan projektiisi!
